previewsEnabled: true

envVarGroups:
  - name: EXAMPLE_ENV_VAR_GROUP
    envVars:
      - key: ENV_VAR_SYNC_FALSE
        sync: false
      - key: ELIXIR_VERSION
        value: 1.12.0

services:
  - name: flask
    type: web
    env: python
    envVars:
      - fromGroup: EXAMPLE_ENV_VAR_GROUP
    buildCommand: pip install -r requirements.txt
    startCommand: printenv && gunicorn app:app
